### ISSUE TITLE
Decorator support

### ISSUE THREAD

**Issue by linbudu599** [egoist/esmon#4]
As ESBuild doesn't support TypeScript decorators syntax, when project contains decorator esmon will not work correctly. A plugin is required to handle decorators compilation, the implemention can be like this:

- on `.ts` file load, read the file content.
- check does decorator exist in this file, by `new RegExp(
  /((?<![(\s]\s*['"])@\w*[\w\d]\s*(?![;])[((?=\s)])/.
)` (use strip-comments package to remove comments which may also contain `@` syntax)
- if decorators are detected, use `transpileModule` export from typescript, and return result as contents.
-  also, if project contains lots of files with decorators, swc can be considered as replacement for tsc(in my experiments they work normally).

**Comment by egoist** [comment]
I'm considering using swc and only use esbuild form bundling, maybe also
make bundling optional, not sure it it's actually useful for other people.

**Comment by egoist** [comment]
esbuild now supports decorators by default, I also added support for `emitDecoratorMetadata` using swc.
