### ISSUE TITLE
Random 'address already in use' error on restart

### ISSUE THREAD

**Issue by IlyaSemenov** [egoist/esmon#5]
If I run: `yarn esmon src/api/server.ts`

I get random errors when I modify files:

```
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:3001
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:68:8)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 3001
```

I wasn't able to reproduce this on a minimal example, and I wasn't able to 'reduce' my code reliably (the error simply appears less frequently). I believe there is a race condition which has something to do with how long does the compilation and/or resource deallocation take. Could it be for instance that you don't actually wait until the 'old' process is fully gone before spawning a new one?

This is macOS 11.3.1, node 16.

**Comment by IlyaSemenov** [comment]
If I add 500 ms delay here after `cmd.kill()`:

https://github.com/egoist/esmon/blob/62102236591ff133f6add023175ea68f7f874e47/src/index.ts#L89-L95

then it works fine. I guess you need to call `waitpid` somehow (if that is possible on Node at all)?

**Comment by IlyaSemenov** [comment]
Unfortunately the fix didn't help. Reload worked for the first few times then stopped (probably because everything had been cached and the compilation became too fast). And honestly I don't see how it should have helped - I don't see `tree-kill` waiting for processes to shut down: https://github.com/pkrumins/node-tree-kill/blob/cb478381547107f5c53362668533f634beff7e6e/index.js#L53

**Comment by IlyaSemenov** [comment]
For comparison, [estrella](https://github.com/rsms/estrella) watch mode works 100% reliably. I like the simplicity of esmon though so would really prefer you to figure this out ;)

**Comment by IlyaSemenov** [comment]
I think that's what does the trick: https://github.com/rsms/estrella/blob/e5b985bd3292ddaa87022b97062be2f18b15b182/src/exec.ts#L477

They attach a listener to `p.on("exit", ...)` and only proceed after it's called (or after 500ms timeout + SIGKILL).

**Comment by egoist** [comment]
that sounds like a solution, PR welcome 😄
